api_endpoint: "http://10.254.138.189:8107"
model: "Qwen2.5-32B-Instruct"
dataset_path: "/raid/vinh/resources/datasets/ProcessBench-250"
output_dir: "/raid/vinh/resources/datasets/ProcessBench-250-graphs"
splits:
  - gsm8k
  - math
  - olympiadbench
  - omnimath
constructor_type: targeted
construction_kwargs:
  max_window_size: 10
generation_kwargs:
  temperature: 0.0
  max_tokens: 4096
sample_size: -1
num_workers: 16