api_endpoint: "http://10.254.138.192:9002"
model: "Meta-Llama-3-70B-Instruct"
dataset_path: "/raid/vinh/resources/datasets/ProcessBench-333"
output_dir: "/raid/vinh/resources/datasets/ProcessBench-333-graphs"
splits:
  - gsm8k
  - math
  - olympiadbench
  - omnimath
constructor_type: hybrid
construction_kwargs:
  max_window_size: 5
  overlap_size: 2
generation_kwargs:
  temperature: 0.0
  max_tokens: 4096
sample_size: -1
num_workers: 16