api_endpoint: "http://10.254.138.189:8107"
model: "Qwen2.5-32B-Instruct"
output_dir: "/raid/vinh/resources/results"
splits:
  - gsm8k
  - math
  - olympiadbench
  - omnimath
verifier_type: sequential
verifier_kwargs:
construction_kwargs:
generation_kwargs:
  temperature: 0.0
  max_tokens: 4096
dataset_path: "/raid/vinh/resources/datasets/ProcessBench"
sample_size: 250
use_voting: false
voting_n: 8
num_workers: 16