api_endpoint: YOUR_API_ENDPOINT
model: SERVED_MODEL
output_dir: YOUR_OUTPUT_DIR
splits:
  - gsm8k
  - math
  - olympiadbench
  - omnimath
verifier_type: logicflow
verifier_kwargs:
  constructor_type: hybrid
  prefix: predecessors
  suffix: null
  prefix_size: -1
  suffix_size: -1
construction_kwargs:
  max_window_size: 5
generation_kwargs:
  temperature: 0.0
  max_tokens: 4096
dataset_path: YOUR_DATASET_PATH
sample_size: -1
use_voting: false
voting_n: 8
num_workers: 16